version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=planner
      - POSTGRES_USER=cuba
      - POSTGRES_PASSWORD=cuba
    volumes:
      - ./deploy/pg_data:/var/lib/postgresql/data
  core_1:
    depends_on:
      - postgres
    image: app-core:latest
    environment:
      - CUBA_CLUSTER_ENABLED=true
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
  core_2:
    depends_on:
      - postgres
    image: app-core:latest
    environment:
      - CUBA_CLUSTER_ENABLED=true
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
  web_1:
    depends_on:
      - core_1
      - core_2
    image: app:latest
    environment:
      - CUBA_CONNECTIONURLLIST=http://core_1:8079/app-core,http://core_2:8079/app-core
  web_2:
    depends_on:
      - core_1
      - core_2
    image: app:latest
    environment:
      - CUBA_CONNECTIONURLLIST=http://core_1:8079/app-core,http://core_2:8079/app-core
  nginx:
    depends_on:
      - web_1
      - web_2
    image: nginx:latest
    volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80