version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=planner
      - POSTGRES_USER=cuba
      - POSTGRES_PASSWORD=cuba
    volumes:
      - ./deploy/pg_data:/var/lib/postgresql/data
  web:
    depends_on:
      - postgres
    image: app:latest
    ports:
    - 80:8080