alter table SESSIONPLANNER_SESSION add constraint FK_SESSIONPLANNER_SESSION_ON_CATEGORY foreign key (CATEGORY_ID) references SYS_CATEGORY(ID);
create index IDX_SESSIONPLANNER_SESSION_ON_CATEGORY on SESSIONPLANNER_SESSION (CATEGORY_ID);
